### ISSUE TITLE
example doesn't work

### ISSUE THREAD

**Issue by marksteven** [HoudiniGraphql/example-sveltekit-todo#1]
Hi Guys,
viewed your video on houdini / graphQL so thought I try it out.

your example to clone
git clone git@github.com:HoudiniGraphql/example-sveltekit-todo.git
did not work do to permissions however

git clone https://github.com/HoudiniGraphql/example-sveltekit-todo.git

worked fine

thought you should know
also I tried using pnpm i which failed so npm i worked fine

thanks for the example

**Comment by jycouet** [comment]
Hi @marksteven, 
To clone a repo with git, you have two options: 
- `ssh` with `git clone git@...`
- `https` with `git clone https@...`
If you want ssh, you should follow some GitHub doc/tuto (Houdini can't do anything on that).
I'll add a note in the readme.

Regarding `pnpm` that failed. Could you explain a bit more the issue?

**Comment by marksteven** [comment]
Hi,
Thanks for getting back to me.
I better explain a bit better sorry.
I was able to clone fine by using 
git clone https://github.com/HoudiniGraphql/example-sveltekit-todo.git

On your page though 
https://github.com/HoudiniGraphql/example-sveltekit-todo
You have 
git clone git@github.com:HoudiniGraphql/example-sveltekit-todo.git
Which doesn't work (at least for me, seems like code is wrong but I'm no expert )
So just letting you know for the next person.

On the pnpm install side 
Once I had cloned the project I tried using my usual pnpm i instead of npm i as it saves space for shared Node module files and usually is very good for that. 
But it didn't work so I used as per your description npm install instead and it all worked.
Was more to let you know that at least for me there seems to be something not quite right.

Now am looking forward to seeing how GraphQl works with svelte.
Thanks for all your hard work here.

**Comment by jycouet** [comment]
Great to read that a new member of Svelte and GraphQL community is joining ✌️

This repo is not setup directly for `pnpm` as we didn't commit a `pnpm-lock.yaml`. 
But still, I have it working just fine. When you say "`But it didn't work`", do you have a log? When and how is it failing?

Here is how it looks on my end: 
![image](https://github.com/HoudiniGraphql/example-sveltekit-todo/assets/5312607/6e77f559-cdc6-4d88-9b92-4cd7bd97e3db)

**Comment by marksteven** [comment]
Hi again,
Thought I would replicate it again my end so I can send you the logs.
So just did that. 
And of course it worked perfectly this time! 
(Even though I had tried 3 times previously yesterday)
So can only assume I might have had an internet issue at the time that I was not aware of,
 so sorry to have wasted your time on this.

**Comment by jycouet** [comment]
No worries. Happy to welcome newcomers 👍
